export const createLibraryTrack = ({
  id,
  title,
  artist,
  bpm,
  key,
  src,
  duration = '00:00',
  artwork,
}) => ({
  id,
  title,
  artist,
  bpm,
  key,
  src,
  duration,
  artwork: artwork ?? `https://picsum.photos/seed/${id}/100/100`,
});

export const TRACK_LIBRARY = [
  createLibraryTrack({
    id: 'hoono-01',
    title: 'Call of Silence 4',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-01.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-02',
    title: 'DECO_27 - Monitoring (Best Friend Remix) feat. Hatsune Miku',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-02.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-03',
    title: 'PORNOGRAFFITTI THE DAY',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-03.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-04',
    title: 'Pocket Monsters OP01 - Aim to Be a Pokemon Master',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-04.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-05',
    title: 'Renai Circulation',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-05.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-06',
    title: 'Rolling Girl feat. Hatsune Miku - Project DIVA Arcade Future Tone',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-06.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-07',
    title: 'ZUTOMAYO - Byoushinwo Kamu',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-07.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-08',
    title: 'Daidaidaidaidaikirai (BIGFIGHT REMIX)',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-08.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-09',
    title: 'ヨルシカ - 千鳥',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-09.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-10',
    title: 'ローリンガール - いおぎりょう Remix',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-10.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-11',
    title: 'ワールドイズマイン [CPK! Remix]',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-11.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-12',
    title: '第六感 feat.東京ゲゲゲイ',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-12.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-13',
    title: 'Kenshi Yonezu - IRIS OUT',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-13.mp3',
  }),
  createLibraryTrack({
    id: 'hoono-14',
    title: 'Kenshi Yonezu - KICK BACK (Frost Children Remix)',
    artist: 'hoono歌單',
    bpm: 120,
    key: '8A',
    src: '/audio/hoono-14.mp3',
  }),
];
